remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme 
title: "Island Tour Guide"
description: "Plan your next vacation using these amazing sites"
gitorg: "https://github.com/shruthim0/dpproject"
google_analytics: